application:
  title: '@project.name@'
  version: '@project.version@'

bookshelf:
  title: "MyBookshelf"
#  capacity: 1000
  version: "v1.0.0"
  license:
    name: "MIT License"
    url: https://opensource.org/licenses/MIT

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshelf
    username: birgit
    password: geheim
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
#    generate-ddl: false
#    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

